
name: Eslint check

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        working-directory: ./application
        run: npm i --ignore-scripts

      - name: Run ESLint
        uses: ninosaurus/eslint-check@v5
        with:
          eslint-config-path: "./application/assets/js/.eslintrc.json"
          custom-directory: "./application"
          repo-token: ${{secrets.GITHUB_TOKEN}}
